import React from 'react';
import { 
  View, 
  Text, 
  TouchableOpacity, 
  StyleSheet, 
  ScrollView, 
  StatusBar 
} from 'react-native';

export default function FeedbackScreen({ data, onRestart }) {
  const score = data?.score ?? "Completed";
  const feedback = data?.feedback ?? "No feedback provided.";

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" backgroundColor="#0B0F19" />
      
      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        {/* Top Badge */}
        <View style={styles.badgeContainer}>
          <View style={styles.aiPoweredBadge}>
            <Text style={styles.badgeSparkle}>🏆</Text>
            <Text style={styles.badgeText}>ASSESSMENT REPORT</Text>
          </View>
        </View>

        {/* Title Section */}
        <View style={styles.headerSection}>
          <Text style={styles.mainTitle}>Interview</Text>
          <Text style={styles.mainTitleGradient}>Evaluated</Text>
          <Text style={styles.subtitle}>
            Here is your final performance breakdown and AI scoring summary.
          </Text>
        </View>

        {/* Score Card */}
        <View style={styles.scoreCard}>
          <Text style={styles.scoreLabel}>OVERALL PERFORMANCE SCORE</Text>
          <Text style={styles.scoreValue}>{score}</Text>
        </View>

        {/* Detailed Feedback Card */}
        <View style={styles.feedbackCard}>
          <View style={styles.cardHeaderRow}>
            <View style={styles.iconBox}>
              <Text style={styles.emoji}>📊</Text>
            </View>
            <View style={styles.cardTextBox}>
              <Text style={styles.cardTitle}>Detailed Analysis</Text>
              <Text style={styles.cardSub}>Generated by local RAG vector evaluations.</Text>
            </View>
          </View>
          
          <View style={styles.divider} />
          
          <Text style={styles.feedbackText}>{feedback}</Text>
        </View>

        {/* Action Button */}
        <TouchableOpacity 
          style={styles.btn} 
          onPress={onRestart}
          activeOpacity={0.8}
        >
          <Text style={styles.btnText}>START NEW SESSION ↺</Text>
        </TouchableOpacity>

        <View style={{ height: 40 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0B0F19' },
  scrollContent: { padding: 20 },
  badgeContainer: { alignItems: 'flex-start', marginBottom: 16 },
  aiPoweredBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1E1B4B', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, borderWidth: 1, borderColor: '#312E81' },
  badgeSparkle: { fontSize: 12, marginRight: 6 },
  badgeText: { color: '#818CF8', fontSize: 11, fontWeight: '800', letterSpacing: 1 },
  headerSection: { marginBottom: 24 },
  mainTitle: { fontSize: 32, fontWeight: '900', color: '#F8FAFC', lineHeight: 36 },
  mainTitleGradient: { fontSize: 32, fontWeight: '900', color: '#818CF8', marginBottom: 10, lineHeight: 36 },
  subtitle: { fontSize: 14, color: '#94A3B8', lineHeight: 20 },
  scoreCard: { backgroundColor: '#1E293B', borderRadius: 24, padding: 24, alignItems: 'center', borderWidth: 1, borderColor: '#334155', marginBottom: 20, shadowColor: '#4F46E5', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.2, shadowRadius: 15, elevation: 8 },
  scoreLabel: { fontSize: 10, fontWeight: '800', color: '#818CF8', letterSpacing: 1, marginBottom: 8 },
  scoreValue: { fontSize: 42, fontWeight: '900', color: '#F8FAFC' },
  feedbackCard: { backgroundColor: '#1E293B', borderRadius: 24, padding: 20, borderWidth: 1, borderColor: '#334155', marginBottom: 24 },
  cardHeaderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  iconBox: { width: 44, height: 44, backgroundColor: '#312E81', borderRadius: 14, justifyContent: 'center', alignItems: 'center', marginRight: 14 },
  emoji: { fontSize: 20 },
  cardTextBox: { flex: 1 },
  cardTitle: { fontSize: 16, fontWeight: '800', color: '#F8FAFC', marginBottom: 2 },
  cardSub: { fontSize: 11, color: '#94A3B8', lineHeight: 15 },
  divider: { height: 1, backgroundColor: '#334155', marginBottom: 16 },
  feedbackText: { fontSize: 14, color: '#E2E8F0', lineHeight: 22 },
  btn: { backgroundColor: '#4F46E5', padding: 16, borderRadius: 12, alignItems: 'center' },
  btnText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900', letterSpacing: 1 }
});